### ISSUE TITLE
Using phantomJS in scala worksheets for dev dom

### ISSUE THREAD

**Issue by austinrivas** [vmunier/play-with-scalajs-example#30]
Recently I have been trying to get my scala worksheets ( IntelliJ ) working for client side dev.

Everything seems to work fine until you actually try to produce dom.

![screen shot 2015-02-16 at 5 54 21 pm](https://cloud.githubusercontent.com/assets/1114054/6222245/2cabf22a-b605-11e4-8324-fe6d73af3e23.png)

Have you or anyone you know successfully wired intelliJ scala worksheets up to PhantomJS / Rhino as a virtual dom?

**Comment by vmunier** [comment]
Hi,
The issue you describe is not related to this example. The mailing list https://groups.google.com/forum/?fromgroups#!forum/scala-js is a better place to ask this question.

**Comment by austinrivas** [comment]
Thanks for pointing me in the right direction
