### ISSUE TITLE
fastOptJS running during test

### ISSUE THREAD

**Issue by Kyprus** [vmunier/play-with-scalajs-example#33]
Every time you run `test` fastOptJS gets run for every js project. As far as I can tell this shouldn't be nessecary and it takes up a good chunk of time when running test a lot. Would it be possible to exclude that when testing?

**Comment by vmunier** [comment]
Hi @Kyprus, it is actually needed to run fastOptJS during `test` for Integration Testing.
For example, this [test](https://github.com/vmunier/play-with-scalajs-example/blob/master/example-server/test/IntegrationSpec.scala) would display `Error loading JavaScript from [http://localhost:19001/assets/exampleclient-fastopt.js]` if fastOptJS was not run during `test`.

**Comment by Kyprus** [comment]
Sorry, I wasn't very clear. What I mean is that fastOptJS will run every time even if there are no changes to the project source. If you run test twice in a row without changing anything fastOptJS will run both times.

**Comment by Kyprus** [comment]
I also just realized I created this issue in the example project and not the actual sbt plugin project. Sorry about that!

**Comment by sjrd** [comment]
That's a bibug of Scala.js itself, which is fixed in master.

**Comment by Kyprus** [comment]
Okay, that's good to hear. Thanks @sjrd
