### ISSUE TITLE
Deploy to Heroku failed

### ISSUE THREAD

**Issue by MysterionRise** [vmunier/play-with-scalajs-example#34]
Hi,

I'm very interested in this project, I've try to migrate to this kind of a project for my current Play app. The problem is, that slug size exceed 300 Mb. Did you face that kind of issues? May be I'm missing something?

!   Compiled slug size: 618.8MB is too large (max is 300MB).
 !   See: http://devcenter.heroku.com/articles/slug-sizefailed

**Comment by vmunier** [comment]
Hi @MysterionRise, 
Thanks for raising the issue. I don't use Heroku, so I don't often test that the deployment still works fine.

But this project is now using the `sbt-heroku` plugin and it fixes the slug size issue.

For reference, I've included the changes of this PR https://github.com/vmunier/play-with-scalajs-example/pull/31 into master.

**Comment by MysterionRise** [comment]
Thanks, @vmunier 

It works very smoothly, slug size reduced from 600 mb to 93 - which is amazing!
