### ISSUE TITLE
Communucation between Scala.js and Play subprojects

### ISSUE THREAD

**Issue by MysterionRise** [vmunier/play-with-scalajs-example#38]
I have a problem now (looks like a common issue for this kind of a project) I want to use i18n messages from Play in Scala.js subproject. So far, I couldn't find a way to do that.

May be you know the way how to do that? Sorry, it not looks like an issue, but more a like usage problem.

**Comment by dejvid** [comment]
Well  i can give you usage tip: We use scala-js only for javascript stuff. Anything that is message to user related we use twirl templates. Twirl templates can be language aware. You can have translated tags preloaded  with twirl template and  you can pass translated message with ajax requests. This way you keep all the translation tags inside one framework. 

Twirl template can be preloaded as  javascript generating twirl that outputs tag->current language translation, html template, as xml, etc. for scala-js to process. 

This is one way of many.

**Comment by vmunier** [comment]
Hi @MysterionRise,

How to use i18n with Scala.js was discussed a bit on gitter https://gitter.im/scala-js/scala-js/archives/2015/05/26.

> You can have translated tags preloaded with twirl template and you can pass translated message with ajax requests.

:+1:

If you have usage questions, I would recommend using either the [Scala.js mailing list](https://groups.google.com/forum/?fromgroups#!forum/scala-js) or one of the gitter channels ([Scala.js](https://gitter.im/scala-js/scala-js), [play-with-scalajs-example](https://gitter.im/vmunier/play-with-scalajs-example)).
