### ISSUE TITLE
[Question] intellij “object index is not a member of package views.html”

### ISSUE THREAD

**Issue by hajime-moto** [vmunier/play-with-scalajs-example#42]
I've post this question on [SO](http://stackoverflow.com/questions/36447560/intellij-object-index-is-not-a-member-of-package-views-html).

I've got Intellij 15.0.5 and I cannot get rid of this error

object index is not a member of package views.
The project I'm trying to checkout is a scalajs play project. Importing this project into Intellij shows the above error. I've read all the other similar question on SO but none of them helped and I've tried the following

Right click the project -> Add framework support -> select "Play 2"
Result: I didn't see any change to my project. When I hit OK, the window disappears but if I try the same the second time. Nothing happens and the window is still there!

Preferences -> Languages & Frameworks -> Play2 -> select "Use Play 2 compiler for this project"
Result: I get this error

Error:Module 'client' production: java.lang.NullPointerException
I've tried

invalidate cache & restart
sbt clean
checkout a fresh new project
But I keep getting the same error in Intellij.

Running sbt compile on command line runs the build successful. But Intellij keeps shows me the above error.

How do I fix this ?

**Comment by vmunier** [comment]
Hello,

Are you having this error in the `Application.scala` file?
Do you have the same error when importing a simple Play project, which does not use Scala.js nor sbt-play-scalajs?

I am using IntelliJ `v2016.1.1` with the Scala plugin `v3.0.1` and I don't seem to have the error you've got.
You can try upgrading your IntelliJ and Scala plugin to see if it fixes the issue.

Cheers,
Vincent

**Comment by hajime-moto** [comment]
Yes I'm getting that error in `Application.scala`. 

I've uninstalled all the version of Intellij I had and reinstalled a fresh copy of `v2016.1` and created a new play project and I'm having the same issue. 

I guess it's nothing to do `play-with-scalajs-example` anymore :(

**Comment by vmunier** [comment]
Yes it looks like it's not related to Scala.js or sbt-play-scalajs, since you could reproduce the issue with a unique Play project.
