### ISSUE TITLE
Error while running the project

### ISSUE THREAD

**Issue by arajajyothibabu** [vmunier/play-with-scalajs-example#43]
Here is the error

> java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.

Help me out of this

**Comment by vmunier** [comment]
Hello,

Have you made some modifications to the example? What version of java are you using?

**Comment by arajajyothibabu** [comment]
Java 1.8
Scala 2.11.7

**Comment by vmunier** [comment]
Do you have this error when you do a fresh clone of the repository, launch sbt and run?
```
git clone git@github.com:vmunier/play-with-scalajs-example.git
sbt
> run
```
I am using Java 1.8.0_45, Scala 2.11.8 and I cannot reproduce your error.

**Comment by arajajyothibabu** [comment]
Actually I have a doubt. Where are the three different projects defined in `build.sbt`. How the application will run without those different projects?

**Comment by vmunier** [comment]
I don't think I understand your question. The `server` project's code is in the the `server` folder, the `client` code is in the `client` folder, same for the `shared` project.

**Comment by arajajyothibabu** [comment]
For me It's saying that they are not SBT projects. They seem to be normal folders. I think we need to define module projects in `build.sbt`

**Comment by vmunier** [comment]
I think I found what you did wrong, I suppose you launched sbt from the server folder.
You need to launch `sbt` from the root folder, i.e. from the `play-with-scalajs-example` folder once you've cloned the repository locally.

**Comment by vmunier** [comment]
@arajajyothibabu Let me know if running `sbt` from the wrong folder was the actual issue.

**Comment by arajajyothibabu** [comment]
@vmunier Thank you It's running.. ! I tried to run after loading the project to IntelliJ. Fresh project after cloning worked fine.
