### ISSUE TITLE
Test code from shared is not shared with client and server

### ISSUE THREAD

**Issue by i-am-the-slime** [vmunier/play-with-scalajs-example#44]
I have some nyaya Generators that I would like to use in both my server and client tests. They are in the shared tests folder. How can I make them accessible without duplicating them and without somehow packaging them into the final JS?

**Comment by vmunier** [comment]
Try changing this line https://github.com/vmunier/play-with-scalajs-example/blob/49a96dd0ec802d274a70447bc0c74b0b9c8ca5ea/build.sbt#L21 to `dependsOn(sharedJvm % "compile;test->test")`. Similar change for the `client` project.

`compile` is a shorthand for `compile->compile`, which means `server` compile scope depends on `sharedJvm` compile scope. `test->test` means `server` test scope depends on `sharedJvm` test scope. (`test` is a shorthand `test->compile`)

**Comment by i-am-the-slime** [comment]
Sauber 👍  I think that worked!
