### ISSUE TITLE
add play generated src in build.sbt

### ISSUE THREAD

**Issue by cuzfrog** [vmunier/play-with-scalajs-example#45]
unmanagedSourceDirectories in Compile <++= baseDirectory { base =>
  Seq(
    base / "server/target/scala-2.11/routes",
    base / "server/target/scala-2.11/twirl"
  )
}

**Comment by vmunier** [comment]
Hello,

Why would you like to add the generated routes and twirl Scala files to your source directories?

**Comment by cuzfrog** [comment]
otherwise Scala IDE cannot resolve .html in views package

**Comment by vmunier** [comment]
When using Eclipse, the error I see is 'object index is not a member of package views.html' in Application.scala. I tried your sbt settings but it does not fix the issue.
Regardless, adding the generated routes and twirl Scala files to the source directories sounds inappropriate to me. 

It's worth noting that this Eclipse error on the Play views is also present when a using a regular Play project (no Scala.js).
