### ISSUE TITLE
unresolved dependency issue

### ISSUE THREAD

**Issue by ganeshchand** [vmunier/play-with-scalajs-example#46]
I cloned the repo and launched SBT and executed run command. I get the following dependency issue. My environment: IntelliJ 2016, OS X El Capitan, Java 7 (tried with Java8 too).
`[error] (server/*:update) sbt.ResolveException: unresolved dependency: org.apache.commons#commons-exec;1.3: org.apache.commons#commons-parent;35!commons-parent.pom(pom.original) origin location must be absolute: file:/Users/username/.m2/repository/org/apache/commons/commons-parent/35/commons-parent-35.pom`

**Comment by vmunier** [comment]
Try to delete `org/apache/commons` from your `.m2` folder and re-run it.

**Comment by vmunier** [comment]
Hi @ganeshchand, have you find a way to resolve your issue?
